[package]
name = "xuid-256-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xuid_256 = { path = "../xuid_256" }
